import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import makeAnimated from 'react-select/animated';
import Tree from 'react-d3-tree';
import Select from 'react-select'
import ReactModal from 'react-modal';


import {
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    UploadOutlined,
    UserOutlined,
    VideoCameraOutlined,
} from '@ant-design/icons';
import { Button, Col, Row, Divider, Space } from 'antd';
import React, { useState, useEffect } from 'react';


const inter = Inter({ subsets: ['latin'] })
const centerStyle: Object = {
    position: 'fixed',
    float: 'right',
    display: 'flex',
    height: '100vh',
    width: '100wh'
};
const styless = {
    position: 'fixed',
};
const options = [
    { value: 'chocolate', label: 'Chocolate' },
    { value: 'strawberry', label: 'Strawberry' },
    { value: 'vanilla', label: 'Vanilla' }
]

export default function Home() {
    const [orgChart, changeChart] = useState({});
    const [femaleArr, femaleGene] = useState([]);
    const [maleArr, maleGene] = useState([]);
    const animatedComponents = makeAnimated();
    const goChart = async (geneMale: Array<string>, geneFemale: Array<string>, gen: boolean) => {
        if (!gen) {
            changeChart({});
            return;
        }
        const body: any = {
            geneFemale: [],
            geneMale: []
        };
        const res = await fetch(`/api/bengalGene`, {
            method: 'POST',
            body: JSON.stringify(body),
        });
        const data = await res.json();
        console.log(data);
        changeChart(data);
        return;

    }
    useEffect(() => {
        console.log('render');
    });
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Divider orientation="center">Bengal Cat Color and Pattern</Divider>
            </div>
            <main className={styles.main} style={{ height: '100vh', width: '100vw' }} >
                <div >
                    <Select closeMenuOnSelect={false}
                        components={animatedComponents}
                        isMulti
                        options={options} />
                    <Select closeMenuOnSelect={false}
                        components={animatedComponents}
                        isMulti
                        options={options} />
                    <br></br>
                    <br></br>
                    <Button onClick={async () => await goChart(femaleArr, maleArr, false)} >重新計算</Button>
                    <Button onClick={async () => await goChart(femaleArr, maleArr, true)} >開始計算</Button>
                    <br></br>
                    <br></br>
                    <Tree style={{ height: '100em', width: '100em' }} data={orgChart} />
                </div>
            </main>
        </>
    )
}
